//
// NewsApiResultsArticles.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct NewsApiResult: Codable, Identifiable, Hashable {

    public var id = UUID()

    public var source: NewsApiResultSource?
    public var author: String?
    public var title: String?
    public var _description: String?
    public var url: String?
    public var urlToImage: String?
    public var publishedAt: Date?
    public var content: String?

    public init(source: NewsApiResultSource? = nil, author: String? = nil, title: String? = nil, _description: String? = nil, url: String? = nil, urlToImage: String? = nil, publishedAt: Date? = nil, content: String? = nil) {
        self.source = source
        self.author = author
        self.title = title
        self._description = _description
        self.url = url
        self.urlToImage = urlToImage
        self.publishedAt = publishedAt
        self.content = content
    }

    public enum CodingKeys: String, CodingKey { 
        case source
        case author
        case title
        case _description = "description"
        case url
        case urlToImage
        case publishedAt
        case content
    }

}

extension NewsApiResult: NewsItemProtocol {
    var header: String {
        return self.title.or("the news header is empty")
    }

    var writer: String {
        return self.author.or("-")
    }

    var description: String {
        return self._description.or("the news body is empty")
    }

    var origin: String {
        return (self.source?.name).or("-")
    }

    var publishingDate: String {
        return (self.publishedAt?.toString(withFormat: "dd.MM.yyyy HH:mm")).or("-")
    }
}
