//
// NewsApiSources.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct NewsApiSources: Codable {

    //public var status: String?
    public var sources: [NewsApiSource]?

    public init(status: String? = nil, sources: [NewsApiSource]? = nil) {
        //self.status = status
        self.sources = sources
    }


}
