//
// NewsApiResults.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct NewsApiResults: Codable {

    public var status: String?
    public var totalResults: Int?
    public var articles: [NewsApiResult]?

    public init(status: String? = nil, totalResults: Int? = nil, articles: [NewsApiResult]? = nil) {
        self.status = status
        self.totalResults = totalResults
        self.articles = articles
    }


}
