//
// TheNewsApiSourcesMeta.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct TheNewsApiSourcesMeta: Codable {

    public var found: Int?
    public var returned: Int?
    public var limit: Int?
    public var page: Int?

    public init(found: Int? = nil, returned: Int? = nil, limit: Int? = nil, page: Int? = nil) {
        self.found = found
        self.returned = returned
        self.limit = limit
        self.page = page
    }


}
