//
// TheNewsApiSources.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

public struct TheNewsApiSources: Codable {

    //public var meta: TheNewsApiSourcesMeta?
    public var data: [TheNewsApiSource]?

    public init(meta: TheNewsApiSourcesMeta? = nil, data: [TheNewsApiSource]? = nil) {
        //self.meta = meta
        self.data = data
    }


}
