//
// TheNewsApiSourcesData.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct TheNewsApiSource: Codable, Identifiable {

    public var id = UUID()

    public var sourceId: String?
    public var domain: String?
    public var language: String?
    public var locale: String?
    public var categories: [String]?

    public init(sourceId: String? = nil, domain: String? = nil, language: String? = nil, locale: String? = nil, categories: [String]? = nil) {
        self.sourceId = sourceId
        self.domain = domain
        self.language = language
        self.locale = locale
        self.categories = categories
    }

    public enum CodingKeys: String, CodingKey { 
        case sourceId = "source_id"
        case domain
        case language
        case locale
        case categories
    }

}

extension TheNewsApiSource: NewsSourceProtocol {
    var title: String {
        return self.domain.or("the news source title is empty")
    }

    var identifier: String {
        return self.domain.or("-")
    }




}
