//
// TheNewsApiResults.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct TheNewsApiResults: Codable {

    public var meta: TheNewsApiSourcesMeta?
    public var data: [TheNewsApiResult]?

    public init(meta: TheNewsApiSourcesMeta? = nil, data: [TheNewsApiResult]? = nil) {
        self.meta = meta
        self.data = data
    }


}
